---
title: "Computer System Notes"
output: word_document
---

Computer:  
- CPU  
- main memory  
- I/O devices  
- System bus  

CPU:  
- control unit  
- arithmetic logic unit (ALU)  
- internal CPU connections  
- registers  

CPU registers:  
- memory address register (MAR): holds address in memory for next read/write instruction    
- memory buffer register (MBR): holds data to be written/read to/from memory
- I/O address register (I/O AR): specifies I/O device    
- I/O data register (I/O DR): exchange data between CPU and I/O  
- program counter (PC): address of next instruction  
- instruction register (IR): current instruction  
- program status word (PSW): status information  

Instruction: Operation Code (OpCode) and/or Operand written in binary code.  
Immediate addressing: when the data comes with the OpCode.  
Implied addressing: when the data is already in registers (before OpCode).  


CPU sppeed: 1 GHz = 1*10^9 Hz (cycles per second).  
To get how many seconds per 1 cycle: reciprocal. 

Interrupts:  
a) program generated, for example errors  
b) hardware generated  
c) timer  
d) I/O  

1 byte = 8 bits  
Word - a sequence of bytes.  
Block - a sequence of words, kilobytes.  

Locality of reference:  
- spatial locality, when data clusters (needed data is in the same block)  
- temporal locality, when data can be reused (for example loops)  

Memory transfer:
-between main memory and cache in blocks  
-between cache and registers in words  

Cache write policy:  
- write through, updates all the time, good for multi-cores  
- write back, updates when block is replaced only  

I/O methods:  
- programmed, cpu send requests to I/O and wait, I/O do the job and when job is done change status, cpu check this status periodically, no interrupts  
- interrupt driven, similiar to programmed, but cpu can do other tasks while waiting and when I/O job is done interrupt signal is send to cpu  
- direct memory access (DMA), cpu send request to DMA controller to do the job, when is done DMA inform cpu

