---
title: "Principles of Programming I Notes"
output: word_document
---
Done: 1-3  


# Basic Math:  
  
- / is standard division; 15 / 10 = 1.5  
- // is floor division; 15 // 10 = 1  
- % is modulo (remainder of division); 15 % 10 = 5  

# Datatypes:  

- text: string  
- numberic: integer, float, complex  
- sequence: list, tuple, range  
- mapping: dictionary  
- sets: set, frozenset  
- boolean: bool  
- binary: bytes, bytearray, memoryview  

Methods vs functions:  
Method "belongs to" given object. They can modify it.  
object.method(arg...)  
Function is not part of the object.  
Function(arg)  

List: can hold various data types, can be nested, is mutable, is ordered.  
Set: store only immutable objects, unordered, does not contain duplicates.  
Dictionary: associate key and value, keys are immutable, values can be mutable.  
Tuple: immutable, ordered group of items. Objects inside tuples can be changed.  
String: immutable list of alphanumerical symbols. 

Reference systems:  
- simple objects (strings, numbers) got equivalent reference to the same item  
- complex objects, even if have the same elements, refer to different objects, it is called aliasing
- aliasing makes that changing values for alias x will change values in alias y  
- to check if items share reference we can use "x is y" comparison  

OOP:  
- constructors, automatically initialize variables  
- polymorphism, using same method for different objects that yields different results  
- polymorphism, in other words, different behaviour for different objects using the same method

\newpage
# Glossary   
Algorithm: process of solving a problem  
Error: Runtime; problem during execution of a program.   
Error: Semantic; program run without errors, but it behaves not as expected.   
Error: Syntax; error due to wrong syntax, like missing paranthesis. In this case program is not able to run.  
Functions: Fruitful; return a value  
Functions: Void; does not return a value  
Program: a sequence of instructions how to perform computation.  
Statement: a unit of code that has some effect  
Variable: Initialization; assignment of initial value  
Variable: Update; assignment of new value which base on old value. Can't be done on immutable data types.    
Variable: Reassignment; assignment of new value which which does not rely on old value  
